
library(hexSticker)

r_blue <- "#2365B0"

sticker("./img/logo assets/mseek_white3.png", package = "",
        p_size = 10,
        p_y = 1.47,
        s_x = 1, s_y = 1.05,
        s_width = 0.82,
        s_height = 0.82,
        spotlight = T,
        l_x = 1.1, l_y = 1.8,
        h_color = "#404040",
        h_fill = "#C41230",
        filename = "./img/logo assets/Hex_Mseek1.png",
        url = "https://metaboseek.com",
        u_size = 14,
        u_x = 1.03,
        dpi = 1200)


sticker("./img/logo assets/Mseek_white_red.png", package = "",
        p_size = 10,
        p_y = 1.47,
        s_x = 1, s_y = 1.05,
        s_width = 0.82,
        s_height = 0.82,
        spotlight = T,
        l_x = 1.2, l_y = 1.8,
        l_width = 3, l_height = 3, l_alpha = 0.4,
        h_color = "#C41230",
        h_fill = "#404040",
        h_size = 1,
        filename = "./img/logo assets/Hex_Mseek2.png",
        url = "https://metaboseek.com",
        u_size = 14,
        u_color = "#FFFFFF",
        u_x = 1.03,
        dpi = 1200)

sticker("./img/logo assets/Mseek_complex.png", package = "",
        p_size = 10,
        p_y = 1.47,
        s_x = 1, s_y = 1.05,
        s_width = 0.75,
        s_height = 0.75,
        spotlight = T,
        l_x = 1.2, l_y = 1.8,
        l_width = 3, l_height = 3, l_alpha = 0.4,
        h_color = "#C41230",
        h_fill = "#404040",
        h_size = 1,
        filename = "./img/logo assets/Hex_Mseek3.png",
        url = "https://metaboseek.com",
        u_size = 14,
        u_color = "#FFFFFF",
        u_x = 1.03,
        dpi = 1200)

sticker("./img/logo assets/Mseek_complex2.png", package = "",
        p_size = 10,
        p_y = 1.47,
        s_x = 1, s_y = 1.0,
        s_width = 0.8,
        s_height = 0.8,
        spotlight = T,
        l_x = 1.2, l_y = 1.8,
        l_width = 3, l_height = 3, l_alpha = 0.4,
        h_color = "#C41230",
        h_fill = "#404040",
        h_size = 1,
        filename = "./img/logo assets/Hex_Mseek4.png",
        url = "https://metaboseek.com",
        u_size = 14,
        u_color = "#FFFFFF",
        u_x = 1.03,
        dpi = 1200)

sticker("./img/logo assets/Mseek_condensed.png", package = "",
        p_size = 10,
        p_y = 1.47,
        s_x = 1, s_y = 1.0,
        s_width = 0.8,
        s_height = 0.8,
        spotlight = T,
        l_x = 1.2, l_y = 1.8,
        l_width = 3, l_height = 3, l_alpha = 0.4,
        h_color = "#C41230",
        h_fill = "#404040",
        h_size = 1,
        filename = "./img/logo assets/Hex_Mseek5.png",
        url = "https://metaboseek.com",
        u_size = 14,
        u_color = "#FFFFFF",
        u_x = 1.03,
        dpi = 1200)


sticker("./img/logo assets/Mseek_complex2.png", package = "",
        p_size = 10,
        p_y = 1.47,
        s_x = 1, s_y = 1.0,
        s_width = 0.8,
        s_height = 0.8,
        spotlight = F,
        l_x = 1.2, l_y = 1.8,
        l_width = 3, l_height = 3, l_alpha = 0.4,
        h_color = "#C41230",
        h_fill = "#404040",
        h_size = 1,
        filename = "./img/logo assets/Hex_Mseek4_nospotlight.png",
        url = "https://metaboseek.com",
        u_size = 14,
        u_color = "#FFFFFF",
        u_x = 1.03,
        dpi = 2400)
